com:
  hideyoshi:
    frontEndPath: ${FRONT_END_PATH}

server:
  error:
    include-stacktrace: on_param
  port: 8070
spring:
  session:
    store-type: JDBC
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:${DATABASE_URL_PSQL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG