com:
  hideyoshi:
    frontEndPath: ${FRONT_END_PATH}
    frontEndConnectionType: ${FRONT_END_CONNECTION_TYPE}
    adminFullname: ${ADMIN_FULLNAME}
    adminEmail: ${ADMIN_EMAIL}
    adminUsername: ${ADMIN_USERNAME}
    adminPassword: ${ADMIN_PASSWORD}
server:
  error:
    include-stacktrace: on_param
  port: ${PORT}
spring:
  session:
    store-type: jdbc
    persistent: true
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG